export interface LocalFontEntry {
  label: string;
  file: string;
}

export const LOCAL_FONT_ENTRIES: LocalFontEntry[] = [
  { label: "ABC Fancy 01", file: "ABC Fancy 01.ttf" },
  { label: "AdobeDevanagari-Bold", file: "AdobeDevanagari-Bold.otf" },
  { label: "AdobeDevanagari-BoldItalic", file: "AdobeDevanagari-BoldItalic.otf" },
  { label: "AdobeDevanagari-Italic", file: "AdobeDevanagari-Italic.otf" },
  { label: "AdobeDevanagari-Regular", file: "AdobeDevanagari-Regular.otf" },
  { label: "AGENCYB", file: "AGENCYB.TTF" },
  { label: "AGENCYR", file: "AGENCYR.TTF" },
  { label: "AKBALTHOM Korea", file: "AKBALTHOM Korea.TTF" },
  { label: "AKBALTHOM TNRB", file: "AKBALTHOM TNRB.TTF" },
  { label: "AKbalthom Chamnap Chhun Version 1.10", file: "AKbalthom Chamnap Chhun Version 1.10.ttf" },
  { label: "AKbalthom Choeung Ek", file: "AKbalthom Choeung Ek.ttf" },
  { label: "AKbalthom DaemPothi", file: "AKbalthom DaemPothi.ttf" },
  { label: "AKbalthom Freehand", file: "AKbalthom Freehand [Version 1.50] 082014.ttf" },
  { label: "AKbalthom HighSchool Version 3.00", file: "AKbalthom HighSchool [Version 3.00].ttf" },
  { label: "AKbalthom HighSchool-Frame", file: "AKbalthom HighSchool-Frame [Version 1.10] 082014.ttf" },
  { label: "AKbalthom HighSchool-Fun", file: "AKbalthom HighSchool-Fun.ttf" },
  { label: "AKbalthom Kampuchearath", file: "AKbalthom Kampuchearath.ttf" },
  { label: "AKbalthom Kbach", file: "AKbalthom Kbach [Version 1.50] 082014.ttf" },
  { label: "AKbalthom Kbach 1", file: "AKbalthom Kbach 1.ttf" },
  { label: "AKbalthom KhmerBasic", file: "AKbalthom KhmerBasic.ttf" },
  { label: "AKbalthom KhmerGothic", file: "AKbalthom KhmerGothic [Version 1.30].ttf" },
  { label: "AKbalthom KhmerHand", file: "AKbalthom KhmerHand.ttf" },
  { label: "AKbalthom Khmer 21st", file: "AKbalthom Khmer 21st.ttf" },
  { label: "AKbalthom Khmer Krom", file: "AKbalthom Khmer Krom.ttf" },
  { label: "AKbalthom Khmer Krom Italic V1.10", file: "AKbalthom Khmer Krom Italic V1.10.ttf" },
  { label: "AKbalthom KhmerLer", file: "AKbalthom KhmerLer [Version 2.00].ttf" },
  { label: "AKbalthom KhmerLight", file: "AKbalthom KhmerLight.ttf" },
  { label: "AKbalthom KhmerNew", file: "AKbalthom KhmerNew [Version 1.30].ttf" },
  { label: "AKbalthom KhmerScript", file: "AKbalthom KhmerScript.ttf" },
  { label: "AKbalthom KmengKmang", file: "AKbalthom KmengKmang.ttf" },
  { label: "AKbalthom KonSmao", file: "AKbalthom KonSmao.ttf" },
  { label: "AKbalthom KrorNhanh", file: "AKbalthom KrorNhanh.ttf" },
  { label: "AKbalthom Koulen 1", file: "AKbalthom Koulen 1.ttf" },
  { label: "AKbalthom Koulen 1 Plus", file: "AKbalthom Koulen 1 Plus.ttf" },
  { label: "AKbalthom Koulen 2", file: "AKbalthom Koulen 2.ttf" },
  { label: "AKbalthom Koulen 2 Plus", file: "AKbalthom Koulen 2 Plus.ttf" },
  { label: "AKbalthom Molleak 2", file: "AKbalthom Molleak 2.ttf" },
  { label: "AKbalthom Molleak 3 Version 1.10", file: "AKbalthom Molleak 3 Version 1.10.ttf" },
  { label: "AKbalthom Moul 1 Plus Version 2.00", file: "AKbalthom Moul 1 Plus Version 2.00.ttf" },
  { label: "AKbalthom Moul 1 Version 2.00", file: "AKbalthom Moul 1 Version 2.00.ttf" },
  { label: "AKbalthom Moul 2 Version 2.00", file: "AKbalthom Moul 2 Version 2.00.ttf" },
  { label: "AKbalthom Moul 3 Version 2.00", file: "AKbalthom Moul 3 Version 2.00.ttf" },
  { label: "AKbalthom Moul 4 Version 1.10", file: "AKbalthom Moul 4 Version 1.10.ttf" },
  { label: "AKbalthom Moul 5", file: "AKbalthom Moul 5.ttf" },
  { label: "AKbalthom Moul 6 V1.05", file: "AKbalthom Moul 6 V1.05.ttf" },
  { label: "AKbalthom Naga Bold", file: "AKbalthom Naga Bold.ttf" },
  { label: "AKbalthom Pheatra C5", file: "AKbalthom Pheatra C5.ttf" },
  { label: "AKbalthom Phnom Penh", file: "AKbalthom Phnom Penh.ttf" },
  { label: "AKbalthom Phnom Sampow", file: "AKbalthom Phnom Sampow.ttf" },
  { label: "AKbalthom Ream", file: "AKbalthom Ream [Version 2.00] 082014.ttf" },
  { label: "AKbalthom Seoul", file: "AKbalthom Seoul.ttf" },
  { label: "AKbalthom Superhero", file: "AKbalthom Superhero.ttf" },
  { label: "AKbalthom SuperheroKH", file: "AKbalthom SuperheroKH.ttf" },
  { label: "AKbalthom Vicheka", file: "AKbalthom Vicheka.ttf" },
  { label: "Akbalthom Molleak 1", file: "Akbalthom Molleak 1.ttf" },
  { label: "ALGER", file: "ALGER.TTF" },
  { label: "ANTQUAB", file: "ANTQUAB.TTF" },
  { label: "ANTQUABI", file: "ANTQUABI.TTF" },
  { label: "ANTQUAI", file: "ANTQUAI.TTF" },
  { label: "ARIALNB", file: "ARIALNB.TTF" },
  { label: "ARIALNBI", file: "ARIALNBI.TTF" },
  { label: "ARIALNI", file: "ARIALNI.TTF" },
  { label: "ARIALN", file: "ARIALN.TTF" },
  { label: "ARLRDBD", file: "ARLRDBD.TTF" },
  { label: "AngTaso", file: "AngTaso.ttf" },
  { label: "AngTasom", file: "AngTasom.ttf" },
  { label: "Angkor", file: "Angkor.ttf" },
  { label: "Angkor_Sovann_NokorReach", file: "Angkor_Sovann_NokorReach.ttf" },
  { label: "AntiochText", file: "AntiochText.ttf" },
  { label: "BaidukOT", file: "BaidukOT.ttf" },
  { label: "BASKVILL", file: "BASKVILL.TTF" },
  { label: "BAUHS93", file: "BAUHS93.TTF" },
  { label: "BELL", file: "BELL.TTF" },
  { label: "BELLB", file: "BELLB.TTF" },
  { label: "BELLI", file: "BELLI.TTF" },
  { label: "BERNHC", file: "BERNHC.TTF" },
  { label: "BKANT", file: "BKANT.TTF" },
  { label: "BOD_B", file: "BOD_B.TTF" },
  { label: "BOD_BI", file: "BOD_BI.TTF" },
  { label: "BOD_BLAR", file: "BOD_BLAR.TTF" },
  { label: "BOD_BLAI", file: "BOD_BLAI.TTF" },
  { label: "BOD_CB", file: "BOD_CB.TTF" },
  { label: "BOD_CBI", file: "BOD_CBI.TTF" },
  { label: "BOD_CI", file: "BOD_CI.TTF" },
  { label: "BOD_CR", file: "BOD_CR.TTF" },
  { label: "BOD_I", file: "BOD_I.TTF" },
  { label: "BOD_PSTC", file: "BOD_PSTC.TTF" },
  { label: "BOD_R", file: "BOD_R.TTF" },
  { label: "BOOKOS", file: "BOOKOS.TTF" },
  { label: "BOOKOSB", file: "BOOKOSB.TTF" },
  { label: "BOOKOSBI", file: "BOOKOSBI.TTF" },
  { label: "BOOKOSI", file: "BOOKOSI.TTF" },
  { label: "BRADHITC", file: "BRADHITC.TTF" },
  { label: "BRITANIC", file: "BRITANIC.TTF" },
  { label: "BROADW", file: "BROADW.TTF" },
  { label: "BRLNSB", file: "BRLNSB.TTF" },
  { label: "BRLNSDB", file: "BRLNSDB.TTF" },
  { label: "BRLNSR", file: "BRLNSR.TTF" },
  { label: "BRUSHSCI", file: "BRUSHSCI.TTF" },
  { label: "BSSYM7", file: "BSSYM7.TTF" },
  { label: "Battambang-Bold", file: "Battambang-Bold.ttf" },
  { label: "Battambang-Regular", file: "Battambang-Regular.ttf" },
  { label: "Bokor", file: "Bokor.ttf" },
  { label: "CALIFB", file: "CALIFB.TTF" },
  { label: "CALIFI", file: "CALIFI.TTF" },
  { label: "CALIFR", file: "CALIFR.TTF" },
  { label: "CALIST", file: "CALIST.TTF" },
  { label: "CALISTB", file: "CALISTB.TTF" },
  { label: "CALISTBI", file: "CALISTBI.TTF" },
  { label: "CALISTI", file: "CALISTI.TTF" },
  { label: "CASTELAR", file: "CASTELAR.TTF" },
  { label: "CENSCBK", file: "CENSCBK.TTF" },
  { label: "CENTAUR", file: "CENTAUR.TTF" },
  { label: "CENTURY", file: "CENTURY.TTF" },
  { label: "CHILLER", file: "CHILLER.TTF" },
  { label: "COLONNA", file: "COLONNA.TTF" },
  { label: "COOPBL", file: "COOPBL.TTF" },
  { label: "COPRGTB", file: "COPRGTB.TTF" },
  { label: "COPRGTL", file: "COPRGTL.TTF" },
  { label: "CURLZ___", file: "CURLZ___.TTF" },
  { label: "Candara", file: "Candara.ttf" },
  { label: "Candarab", file: "Candarab.ttf" },
  { label: "Candarai", file: "Candarai.ttf" },
  { label: "Candaral", file: "Candaral.ttf" },
  { label: "Candarali", file: "Candarali.ttf" },
  { label: "Candaraz", file: "Candaraz.ttf" },
  { label: "ChantreaSRui_Low", file: "ChantreaSRui_Low.ttf" },
  { label: "ChantreaSRui_New", file: "ChantreaSRui_New.ttf" },
  { label: "ChantreaUI", file: "ChantreaUI.ttf" },
  { label: "Chenla", file: "Chenla.ttf" },
  { label: "Content-Bold", file: "Content-Bold.ttf" },
  { label: "Content-Regular", file: "Content-Regular.ttf" },
  { label: "DH-Rongdomrey", file: "DH-Rongdomrey.ttf" },
  { label: "DUBAI-BOLD", file: "DUBAI-BOLD.TTF" },
  { label: "DUBAI-LIGHT", file: "DUBAI-LIGHT.TTF" },
  { label: "DUBAI-MEDIUM", file: "DUBAI-MEDIUM.TTF" },
  { label: "DUBAI-REGULAR", file: "DUBAI-REGULAR.TTF" },
  { label: "DRPUwmgraduate", file: "DRPUwmgraduate.TTF" },
  { label: "DRPUwmtransport1", file: "DRPUwmtransport1.TTF" },
  { label: "DaunKeo", file: "DaunKeo.ttf" },
  { label: "DaunPov", file: "DaunPov.ttf" },
  { label: "DaunTep", file: "DaunTep.ttf" },
  { label: "DaunTeav", file: "DaunTeav.ttf" },
  { label: "Daunsok", file: "Daunsok.ttf" },
  { label: "Doulos SIL Regular", file: "Doulos SIL Regular.ttf" },
  { label: "Dosis-SemiBold", file: "Dosis-SemiBold.ttf" },
  { label: "ELEPHNT", file: "ELEPHNT.TTF" },
  { label: "ELEPHNTI", file: "ELEPHNTI.TTF" },
  { label: "ENGR", file: "ENGR.TTF" },
  { label: "ERASBD", file: "ERASBD.TTF" },
  { label: "ERASDEMI", file: "ERASDEMI.TTF" },
  { label: "ERASLGHT", file: "ERASLGHT.TTF" },
  { label: "ERASMD", file: "ERASMD.TTF" },
  { label: "FELIXTI", file: "FELIXTI.TTF" },
  { label: "FORTE", file: "FORTE.TTF" },
  { label: "FRABK", file: "FRABK.TTF" },
  { label: "FRABKIT", file: "FRABKIT.TTF" },
  { label: "FRADM", file: "FRADM.TTF" },
  { label: "FRADMCN", file: "FRADMCN.TTF" },
  { label: "FRADMIT", file: "FRADMIT.TTF" },
  { label: "FRAMDCN", file: "FRAMDCN.TTF" },
  { label: "FRAHV", file: "FRAHV.TTF" },
  { label: "FRAHVIT", file: "FRAHVIT.TTF" },
  { label: "FREESCPT", file: "FREESCPT.TTF" },
  { label: "FRSCRIPT", file: "FRSCRIPT.TTF" },
  { label: "FTLTLT", file: "FTLTLT.TTF" },
  { label: "Fasthand-Regular", file: "Fasthand-Regular.ttf" },
  { label: "Freehand", file: "Freehand.ttf" },
  { label: "GARA", file: "GARA.TTF" },
  { label: "GARABD", file: "GARABD.TTF" },
  { label: "GARAIT", file: "GARAIT.TTF" },
  { label: "GIL_____", file: "GIL_____.TTF" },
  { label: "GILB____", file: "GILB____.TTF" },
  { label: "GILBI___", file: "GILBI___.TTF" },
  { label: "GILC____", file: "GILC____.TTF" },
  { label: "GILI____", file: "GILI____.TTF" },
  { label: "GILLUBCD", file: "GILLUBCD.TTF" },
  { label: "GILSANUB", file: "GILSANUB.TTF" },
  { label: "GIGI", file: "GIGI.TTF" },
  { label: "GLECB", file: "GLECB.TTF" },
  { label: "GLSNECB", file: "GLSNECB.TTF" },
  { label: "GOTHIC", file: "GOTHIC.TTF" },
  { label: "GOTHICB", file: "GOTHICB.TTF" },
  { label: "GOTHICBI", file: "GOTHICBI.TTF" },
  { label: "GOTHICI", file: "GOTHICI.TTF" },
  { label: "GOUDOS", file: "GOUDOS.TTF" },
  { label: "GOUDOSB", file: "GOUDOSB.TTF" },
  { label: "GOUDOSI", file: "GOUDOSI.TTF" },
  { label: "GOUDYSTO", file: "GOUDYSTO.TTF" },
  { label: "Gabriola", file: "Gabriola.ttf" },
  { label: "HARLOWSI", file: "HARLOWSI.TTF" },
  { label: "HARNGTON", file: "HARNGTON.TTF" },
  { label: "HATTEN", file: "HATTEN.TTF" },
  { label: "HTOWERT", file: "HTOWERT.TTF" },
  { label: "HTOWERTI", file: "HTOWERTI.TTF" },
  { label: "HPSimplified_Bd", file: "HPSimplified_Bd.ttf" },
  { label: "HPSimplified_BdIt", file: "HPSimplified_BdIt.ttf" },
  { label: "HPSimplified_It", file: "HPSimplified_It.ttf" },
  { label: "HPSimplified_Lt", file: "HPSimplified_Lt.ttf" },
  { label: "HPSimplified_LtIt", file: "HPSimplified_LtIt.ttf" },
  { label: "HPSimplified_Rg", file: "HPSimplified_Rg.ttf" },
  { label: "Hanumanb", file: "Hanumanb.ttf" },
  { label: "himalaya", file: "himalaya.ttf" },
  { label: "holomdl2", file: "holomdl2.ttf" },
  { label: "IMPRISHA", file: "IMPRISHA.TTF" },
  { label: "INFROMAN", file: "INFROMAN.TTF" },
  { label: "ITCBLKAD", file: "ITCBLKAD.TTF" },
  { label: "ITCEDSCR", file: "ITCEDSCR.TTF" },
  { label: "ITCKRIST", file: "ITCKRIST.TTF" },
  { label: "Inkfree", file: "Inkfree.ttf" },
  { label: "JOKERMAN", file: "JOKERMAN.TTF" },
  { label: "JUICE___", file: "JUICE___.TTF" },
  { label: "javatext", file: "javatext.ttf" },
  { label: "KDJayavarman1", file: "KDJayavarman1.ttf" },
  { label: "KH ABC FANCY 01 Italic", file: "KH ABC FANCY 01 Italic.ttf" },
  { label: "KH MPS", file: "KH MPS.ttf" },
  { label: "KH MPS Jrung", file: "KH MPS Jrung.ttf" },
  { label: "KHMCHANTHA", file: "KHMCHANTHA.ttf" },
  { label: "KHMCHRIENG1", file: "KHMCHRIENG1.ttf" },
  { label: "KHMERKEP", file: "KHMERKEP.ttf" },
  { label: "KHMKAMPOT", file: "KHMKAMPOT.ttf" },
  { label: "KHMKAMPONGTRACH", file: "KHMKAMPONGTRACH.ttf" },
  { label: "KHMKOLAB", file: "KHMKOLAB.ttf" },
  { label: "KHMMOOL", file: "KHMMOOL.ttf" },
  { label: "KHMMOOL1", file: "KHMMOOL1.ttf" },
  { label: "KHMERMEF1", file: "KHMERMEF1.ttf" },
  { label: "KHMERMEF2", file: "KHMERMEF2.ttf" },
  { label: "KHMNETTRA", file: "KHMNETTRA.ttf" },
  { label: "KHMOLD", file: "KHMOLD.ttf" },
  { label: "KHMWATPHNOM", file: "KHMWATPHNOM.ttf" },
  { label: "KUnKhmer", file: "KunKhmer.ttf" },
  { label: "KdamThmor-Regular", file: "KdamThmor-Regular.ttf" },
  { label: "Kantumruy-Bold", file: "Kantumruy-Bold.ttf" },
  { label: "Kantumruy-Light", file: "Kantumruy-Light.ttf" },
  { label: "Kantumruy-Regular", file: "Kantumruy-Regular.ttf" },
  { label: "Kh Ang B.Rodtha", file: "Kh Ang B.Rodtha.ttf" },
  { label: "Kh Ang Bokor New Version 2.00", file: "Kh Ang Bokor New Version 2.00.ttf" },
  { label: "Kh Ang Chittbous", file: "Kh Ang Chittbous.ttf" },
  { label: "Kh Ang FreeHand", file: "Kh Ang FreeHand.ttf" },
  { label: "Kh Ang Hand-T.Chhim (V.1.30)", file: "Kh Ang Hand-T.Chhim (V.1.30).ttf" },
  { label: "Kh Ang Hand-T.Chhim 2", file: "Kh Ang Hand-T.Chhim 2.ttf" },
  { label: "Kh Ang KanTout", file: "Kh Ang KanTout.ttf" },
  { label: "Kh Ang Kampaeng Thmor", file: "Kh Ang Kampaeng Thmor.ttf" },
  { label: "Kh Ang Kbach Seda", file: "Kh Ang Kbach Seda.ttf" },
  { label: "Kh Ang Klen", file: "Kh Ang Klen.ttf" },
  { label: "Kh Ang Komutt A", file: "Kh Ang Komutt A.ttf" },
  { label: "Kh Ang Komutt B", file: "Kh Ang Komutt B.ttf" },
  { label: "Kh Ang Kouteok", file: "Kh Ang Kouteok.ttf" },
  { label: "Kh Ang Kraaochhouk", file: "Kh Ang Kraaochhouk.ttf" },
  { label: "Kh Ang Ktomp", file: "Kh Ang Ktomp.ttf" },
  { label: "Kh Ang LetfHand", file: "Kh Ang LetfHand.ttf" },
  { label: "Kh Ang Link", file: "Kh Ang Link.ttf" },
  { label: "Kh Ang Moul Seda", file: "Kh Ang Moul Seda [V.2.30].ttf" },
  { label: "Kh Ang Moul Toathmor", file: "Kh Ang Moul Toathmor.ttf" },
  { label: "Kh Ang MoulHand", file: "Kh Ang MoulHand.ttf" },
  { label: "Kh Ang MoulHand 2", file: "Kh Ang MoulHand 2.ttf" },
  { label: "Kh Ang Mura", file: "Kh Ang Mura.ttf" },
  { label: "Kh Ang MuraFastHand", file: "Kh Ang MuraFastHand.ttf" },
  { label: "Kh Ang MuraHand", file: "Kh Ang MuraHand.ttf" },
  { label: "Kh Ang MuraHand 2", file: "Kh Ang MuraHand 2.ttf" },
  { label: "Kh Ang NaKry", file: "Kh Ang NaKry.ttf" },
  { label: "Kh Ang NiTean", file: "Kh Ang NiTean.ttf" },
  { label: "Kh Ang NiTean 2", file: "Kh Ang NiTean 2.ttf" },
  { label: "Kh Ang North", file: "Kh Ang North.ttf" },
  { label: "Kh Ang PeaNor", file: "Kh Ang PeaNor.ttf" },
  { label: "Kh Ang PeaNorent", file: "Kh Ang PeaNorent.ttf" },
  { label: "Kh Ang Penh", file: "Kh Ang Penh.ttf" },
  { label: "Kh Ang PheaSaKhmer", file: "Kh Ang PheaSaKhmer.ttf" },
  { label: "Kh Ang PhkayProek", file: "Kh Ang PhkayProek.ttf" },
  { label: "Kh Ang Pothisal", file: "Kh Ang Pothisal [Version 2.00].ttf" },
  { label: "Kh Ang R.Jrung", file: "Kh Ang R.Jrung.ttf" },
  { label: "Kh Ang Rooster", file: "Kh Ang Rooster.ttf" },
  { label: "Kh Ang Samnadaichas 1.10", file: "Kh Ang Samnadaichas 1.10.ttf" },
  { label: "Kh Ang Silbak", file: "Kh Ang Silbak.ttf" },
  { label: "Kh Ang TaPenh", file: "Kh Ang TaPenh.ttf" },
  { label: "Kh Ang Theara MS", file: "Kh Ang Theara MS.ttf" },
  { label: "Kh Ang Theara MS Plus", file: "Kh Ang Theara MS Plus.ttf" },
  { label: "Kh Ang Thmorkream", file: "Kh Ang Thmorkream.ttf" },
  { label: "Kh Ang ToaThmor", file: "Kh Ang ToaThmor.ttf" },
  { label: "Kh Ang ToaThmor 2", file: "Kh Ang ToaThmor 2.ttf" },
  { label: "Kh Ang ToaThmor 3", file: "Kh Ang ToaThmor 3.ttf" },
  { label: "Kh Ang Toathmor Kbach", file: "Kh Ang Toathmor Kbach.ttf" },
  { label: "Kh Ang Vassa", file: "Kh Ang Vassa.ttf" },
  { label: "Kh Ang Vihearsuor", file: "Kh Ang Vihearsuor.ttf" },
  { label: "Kh Ang Writehand", file: "Kh Ang Writehand.ttf" },
  { label: "Kh BL BrushHand", file: "Kh BL BrushHand.ttf" },
  { label: "Kh BL LazyDistorted", file: "Kh BL LazyDistorted.ttf" },
  { label: "Kh BL LazyOutline", file: "Kh BL LazyOutline.ttf" },
  { label: "Kh BL LazySmooth", file: "Kh BL LazySmooth.ttf" },
  { label: "Kh CN Star", file: "Kh CN Star.ttf" },
  { label: "Kh Digital Thom", file: "Kh Digital Thom.ttf" },
  { label: "Kh Jrung Thom", file: "Kh Jrung Thom.ttf" },
  { label: "Kh KompongThom - Bunly (Beta)", file: "Kh KompongThom - Bunly (Beta).ttf" },
  { label: "Kh MPS Fasthand", file: "Kh MPS Fasthand.ttf" },
  { label: "Kh Pen Wappathor", file: "Kh Pen Wappathor.ttf" },
  { label: "Kh Prey Veng", file: "Kh Prey Veng.ttf" },
  { label: "Kh SN Beysach", file: "Kh SN Beysach.ttf" },
  { label: "Kh SN Kampongsom", file: "Kh SN Kampongsom.ttf" },
  { label: "Kh SN Preytakoy", file: "Kh SN Preytakoy.ttf" },
  { label: "Kh SomborPreyKok - Bunly (beta)", file: "Kh SomborPreyKok - Bunly (beta).ttf" },
  { label: "Kh Writhand (1)", file: "Kh  Writhand (1).ttf" },
  { label: "Kh Writehand Jrung", file: "Kh Writehand Jrung.ttf" },
  { label: "Kh itkonkhmer", file: "kh itkonkhmer.ttf" },
  { label: "Kh itseombel Jrung - bunly", file: "Kh itseombel Jrung - bunly.ttf" },
  { label: "Kh itsupport4kh", file: "kh itsupport4kh.ttf" },
  { label: "Kh Kompong Chhnang", file: "kh Kompong Chhnang.ttf" },
  { label: "Kh-Battambang", file: "Kh-Battambang.ttf" },
  { label: "Kh-Bokor", file: "Kh-Bokor.ttf" },
  { label: "Kh-Content", file: "Kh-Content.ttf" },
  { label: "Kh-Dangrek", file: "Kh-Dangrek.ttf" },
  { label: "Kh-Fasthand", file: "Kh-Fasthand.ttf" },
  { label: "Kh-Freehand", file: "Kh-Freehand.ttf" },
  { label: "Kh-Kangrey", file: "Kh-Kangrey.ttf" },
  { label: "Kh-KoulenL", file: "Kh-KoulenL.ttf" },
  { label: "Kh-Koulen", file: "Kh-Koulen.ttf" },
  { label: "Kh-Metal-Chrieng", file: "Kh-Metal-Chrieng.ttf" },
  { label: "Kh-MithSalaPali-v2", file: "Kh-MithSalaPali-v2.ttf" },
  { label: "Kh-Muol", file: "Kh-Muol.ttf" },
  { label: "Kh-Muol-Pali", file: "Kh-Muol-Pali.ttf" },
  { label: "Kh-Siemreap", file: "Kh-Siemreap.ttf" },
  { label: "Kh-System", file: "Kh-System.ttf" },
  { label: "Kh Kakada Bati", file: "Kh Kakada Bati [Version 1.10].ttf" },
  { label: "KhPreyVeng", file: "KhPreyVeng.ttf" },
  { label: "KhUniF1", file: "KhUniF1.ttf" },
  { label: "KhUniL1", file: "KhUniL1.ttf" },
  { label: "KhUniN2", file: "KhUniN2.ttf" },
  { label: "KhUniR1", file: "KhUniR1.ttf" },
  { label: "KhUniR2", file: "KhUniR2.ttf" },
  { label: "KhUniSerif", file: "KhUniSerif.ttf" },
  { label: "Khmer", file: "Khmer.ttf" },
  { label: "Khmer Banteay Srey", file: "Khmer Banteay Srey.ttf" },
  { label: "Khmer Banteay Srey B", file: "Khmer Banteay Srey B.ttf" },
  { label: "Khmer Banteay Srey L", file: "Khmer Banteay Srey L.ttf" },
  { label: "Khmer Beginner", file: "Khmer Beginner.ttf" },
  { label: "Khmer CN Battambang", file: "Khmer CN Battambang.ttf" },
  { label: "Khmer CN Bone", file: "Khmer CN Bone.ttf" },
  { label: "Khmer CN EkPhnom", file: "Khmer CN EkPhnom.ttf" },
  { label: "Khmer CN Kam Rieng", file: "Khmer CN Kam Rieng.ttf" },
  { label: "Khmer CN Kam Rieng V2", file: "Khmer CN Kam Rieng V2.ttf" },
  { label: "Khmer CN Kampingpouy", file: "Khmer CN Kampingpouy.ttf" },
  { label: "Khmer CN Kselus", file: "Khmer CN Kselus.ttf" },
  { label: "Khmer CN Otaki", file: "Khmer CN Otaki.ttf" },
  { label: "Khmer CN Phnom Sampao", file: "Khmer CN Phnom Sampao.ttf" },
  { label: "Khmer CN Poipet", file: "Khmer CN Poipet.ttf" },
  { label: "Khmer CN Preykonkla", file: "Khmer CN Preykonkla.ttf" },
  { label: "Khmer CN Samlot", file: "Khmer CN Samlot.ttf" },
  { label: "Khmer CN Star", file: "Khmer CN Star.ttf" },
  { label: "Khmer CN Stueng Songke", file: "Khmer CN Stueng Songke.ttf" },
  { label: "Khmer CN ThmorKol", file: "Khmer CN ThmorKol.ttf" },
  { label: "Khmer CN hand", file: "Khmer CN hand.ttf" },
  { label: "Khmer CN lazywrite", file: "Khmer CN lazywrite.ttf" },
  { label: "Khmer DonBosco", file: "Khmer DonBosco.ttf" },
  { label: "Khmer Element", file: "Khmer Element.ttf" },
  { label: "KhmerKCSvayUni", file: "KhmerKCSvayUni.ttf" },
  { label: "KhmerMuol", file: "KhmerMuol.ttf" },
  { label: "KhmerNagari", file: "KhmerNagari.ttf" },
  { label: "KhmerOS", file: "KhmerOS.ttf" },
  { label: "KhmerOSApsra", file: "KhmerOSApsra.ttf" },
  { label: "KhmerOSbattambang", file: "KhmerOSbattambang.ttf" },
  { label: "KhmerOSbokor", file: "KhmerOSbokor.ttf" },
  { label: "KhmerOSclassic", file: "KhmerOSclassic.ttf" },
  { label: "KhmerOScontent", file: "KhmerOScontent.ttf" },
  { label: "KhmerOSfasthand", file: "KhmerOSfasthand.ttf" },
  { label: "KhmerOSfreehand", file: "KhmerOSfreehand.ttf" },
  { label: "KhmerOSkiensvay", file: "KhmerOSkiensvay.ttf" },
  { label: "KhmerOSmetalchrieng", file: "KhmerOSmetalchrieng.ttf" },
  { label: "KhmerOSmuol", file: "KhmerOSmuol.ttf" },
  { label: "KhmerOSmuollight", file: "KhmerOSmuollight.ttf" },
  { label: "KhmerOSmuolpali", file: "KhmerOSmuolpali.ttf" },
  { label: "KhmerOSniroth", file: "KhmerOSniroth.ttf" },
  { label: "KhmerOSsiemreap", file: "KhmerOSsiemreap.ttf" },
  { label: "KhmerOSsys", file: "KhmerOSsys.ttf" },
  { label: "KhmerOSwatphnom", file: "KhmerOSwatphnom.ttf" },
  { label: "Khmer Pailin", file: "Khmer Pailin.ttf" },
  { label: "Khmer Pen Eng", file: "Khmer Pen Eng.ttf" },
  { label: "Khmer Pen Kang", file: "Khmer Pen Kang.ttf" },
  { label: "Khmer Pen SvR", file: "Khmer Pen SvR.ttf" },
  { label: "Khmer Pen Svayreing", file: "Khmer Pen Svayreing.ttf" },
  { label: "Khmer Pen-Surin", file: "Khmer Pen-Surin.ttf" },
  { label: "Khmer Rotanak Angkor Demo 02", file: "Khmer Rotanak Angkor Demo 02.ttf" },
  { label: "KhmerRotanakTraiyB", file: "KhmerRotanakTraiyB.ttf" },
  { label: "KhmerSerif", file: "KhmerSerif.ttf" },
  { label: "Khmer SN Kampongcham", file: "Khmer SN Kampongcham.ttf" },
  { label: "Khmer SN Kampot", file: "Khmer SN Kampot.ttf" },
  { label: "Khmer Savuth Pen", file: "Khmer Savuth Pen.ttf" },
  { label: "Khmer Savuth Pen2", file: "Khmer Savuth Pen2.ttf" },
  { label: "Khmer Sem Sarun", file: "Khmer Sem Sarun.ttf" },
  { label: "Khmer Sharp", file: "Khmer Sharp.ttf" },
  { label: "KhmerTelecommunication", file: "KhmerTelecommunication.ttf" },
  { label: "KhmerUI", file: "KhmerUI.ttf" },
  { label: "KhmerUIb", file: "KhmerUIb.ttf" },
  { label: "Khmer chamnanit", file: "Khmer chamnanit.ttf" },
  { label: "Khmer sexy", file: "Khmer sexy.ttf" },
  { label: "Khmer-Angkulileka v2", file: "Khmer-Angkulileka v2.ttf" },
  { label: "Khmer-Khao-I-Dang", file: "Khmer-Khao-I-Dang.ttf" },
  { label: "Khmer-Pen Teu", file: "Khmer-Pen Teu.ttf" },
  { label: "Khmer-PenChantrea", file: "Khmer-PenChantrea.ttf" },
  { label: "KhmerDLStation TNRB", file: "KhmerDLStation TNRB.ttf" },
  { label: "Khmvanara", file: "Khmvanara.ttf" },
  { label: "Khmviravuth", file: "Khmviravuth.ttf" },
  { label: "Koulen", file: "Koulen.ttf" },
  { label: "KUNSTLER", file: "KUNSTLER.TTF" },
  { label: "LBRITE", file: "LBRITE.TTF" },
  { label: "LBRITED", file: "LBRITED.TTF" },
  { label: "LBRITEDI", file: "LBRITEDI.TTF" },
  { label: "LBRITEI", file: "LBRITEI.TTF" },
  { label: "LCALLIG", file: "LCALLIG.TTF" },
  { label: "LEELAWAD", file: "LEELAWAD.TTF" },
  { label: "LEELAWDB", file: "LEELAWDB.TTF" },
  { label: "LFAX", file: "LFAX.TTF" },
  { label: "LFAXD", file: "LFAXD.TTF" },
  { label: "LFAXDI", file: "LFAXDI.TTF" },
  { label: "LFAXI", file: "LFAXI.TTF" },
  { label: "LHANDW", file: "LHANDW.TTF" },
  { label: "LIMONF1_", file: "LIMONF1_.TTF" },
  { label: "LIMONF2_", file: "LIMONF2_.TTF" },
  { label: "LIMONF3_", file: "LIMONF3_.TTF" },
  { label: "LIMONF4_", file: "LIMONF4_.TTF" },
  { label: "LIMONF5_", file: "LIMONF5_.TTF" },
  { label: "LIMONF6_", file: "LIMONF6_.TTF" },
  { label: "LIMONF7_", file: "LIMONF7_.TTF" },
  { label: "LIMONR1_", file: "LIMONR1_.TTF" },
  { label: "LIMONR2_", file: "LIMONR2_.TTF" },
  { label: "LIMONR3_", file: "LIMONR3_.TTF" },
  { label: "LIMONR4_", file: "LIMONR4_.TTF" },
  { label: "LIMONR5_", file: "LIMONR5_.TTF" },
  { label: "LIMONS1_", file: "LIMONS1_.TTF" },
  { label: "LIMONS2_", file: "LIMONS2_.TTF" },
  { label: "LIMONS3_", file: "LIMONS3_.TTF" },
  { label: "LIMONS4_", file: "LIMONS4_.TTF" },
  { label: "LIMONS5_", file: "LIMONS5_.TTF" },
  { label: "LIMONS6_", file: "LIMONS6_.TTF" },
  { label: "LIMONS7_", file: "LIMONS7_.TTF" },
  { label: "LMNF1", file: "LMNF1.TTF" },
  { label: "LMNF2", file: "LMNF2.TTF" },
  { label: "LMNF3", file: "LMNF3.TTF" },
  { label: "LMNF4", file: "LMNF4.TTF" },
  { label: "LMNF5", file: "LMNF5.TTF" },
  { label: "LMNF6", file: "LMNF6.TTF" },
  { label: "LMNF7", file: "LMNF7.TTF" },
  { label: "LMNS1", file: "LMNS1.TTF" },
  { label: "LMNS2", file: "LMNS2.TTF" },
  { label: "LMNS2D", file: "LMNS2D.ttf" },
  { label: "LMNS3", file: "LMNS3.TTF" },
  { label: "LMNS4", file: "LMNS4.TTF" },
  { label: "LMNS5", file: "LMNS5.TTF" },
  { label: "LMNS6", file: "LMNS6.TTF" },
  { label: "LMNS7", file: "LMNS7.TTF" },
  { label: "LMNR1", file: "LMNR1.TTF" },
  { label: "LMNR2", file: "LMNR2.TTF" },
  { label: "LMNR3", file: "LMNR3.TTF" },
  { label: "LMNR4", file: "LMNR4.TTF" },
  { label: "LMNR5", file: "LMNR5.TTF" },
  { label: "LSANS", file: "LSANS.TTF" },
  { label: "LSANSD", file: "LSANSD.TTF" },
  { label: "LSANSDI", file: "LSANSDI.TTF" },
  { label: "LSANSI", file: "LSANSI.TTF" },
  { label: "LTYPEB", file: "LTYPEB.TTF" },
  { label: "LTYPEBO", file: "LTYPEBO.TTF" },
  { label: "LTYPEO", file: "LTYPEO.TTF" },
  { label: "LTYPE", file: "LTYPE.TTF" },
  { label: "Lato-Black", file: "Lato-Black.ttf" },
  { label: "Lato-Bold", file: "Lato-Bold.ttf" },
  { label: "Lato-Regular", file: "Lato-Regular.ttf" },
  { label: "LeelaUIb", file: "LeelaUIb.ttf" },
  { label: "LeelUIsl", file: "LeelUIsl.ttf" },
  { label: "LeelawUI", file: "LeelawUI.ttf" },
  { label: "Limonf_h", file: "Limonf_h.ttf" },
  { label: "Limonf_s", file: "Limonf_s.ttf" },
  { label: "Limonr_h", file: "Limonr_h.ttf" },
  { label: "Limonr_l", file: "Limonr_l.ttf" },
  { label: "Limonr_s", file: "Limonr_s.ttf" },
  { label: "Limons0", file: "Limons0.ttf" },
  { label: "Limons_b", file: "Limons_b.ttf" },
  { label: "Limons_h", file: "Limons_h.ttf" },
  { label: "Limons_l", file: "Limons_l.ttf" },
  { label: "Limons_s", file: "Limons_s.ttf" },
  { label: "Lmnf8", file: "Lmnf8.ttf" },
  { label: "MAGNETOB", file: "MAGNETOB.TTF" },
  { label: "MAIAN", file: "MAIAN.TTF" },
  { label: "MATURASC", file: "MATURASC.TTF" },
  { label: "MISTRAL", file: "MISTRAL.TTF" },
  { label: "MOD20", file: "MOD20.TTF" },
  { label: "MSUIGHUB", file: "MSUIGHUB.TTF" },
  { label: "MSUIGHUR", file: "MSUIGHUR.TTF" },
  { label: "MTCORSVA", file: "MTCORSVA.TTF" },
  { label: "MTEXTRA", file: "MTEXTRA.TTF" },
  { label: "Metal", file: "Metal.ttf" },
  { label: "Mo5V56", file: "Mo5V56.ttf" },
  { label: "Mo5V56Bu", file: "Mo5V56Bu.ttf" },
  { label: "Mo5V56MO", file: "Mo5V56MO.ttf" },
  { label: "Mo5V56dc", file: "Mo5V56dc.ttf" },
  { label: "Mo5V56di", file: "Mo5V56di.ttf" },
  { label: "Mo5V56do", file: "Mo5V56do.ttf" },
  { label: "Mo5V56hi", file: "Mo5V56hi.ttf" },
  { label: "Mo5V56i", file: "Mo5V56i.ttf" },
  { label: "Mo5V56xs", file: "Mo5V56xs.ttf" },
  { label: "Mo8V56", file: "Mo8V56.ttf" },
  { label: "Mo8V56i", file: "Mo8V56i.ttf" },
  { label: "Mo9V55", file: "Mo9V55.ttf" },
  { label: "Mondulkiri-B", file: "Mondulkiri-B.ttf" },
  { label: "Mondulkiri-BI", file: "Mondulkiri-BI.ttf" },
  { label: "Mondulkiri-I", file: "Mondulkiri-I.ttf" },
  { label: "Mondulkiri-R", file: "Mondulkiri-R.ttf" },
  { label: "Montserrat-Regular", file: "Montserrat-Regular.ttf" },
  { label: "Moul", file: "Moul.ttf" },
  { label: "Moulpali", file: "Moulpali.ttf" },
  { label: "MyanmarSansPro", file: "MyanmarSansPro.ttf" },
  { label: "NIAGENG", file: "NIAGENG.TTF" },
  { label: "NIAGSOL", file: "NIAGSOL.TTF" },
  { label: "NiDAAngkor", file: "NiDAAngkor.ttf" },
  { label: "NiDABayon", file: "NiDABayon.ttf" },
  { label: "NiDAChenla", file: "NiDAChenla.ttf" },
  { label: "NiDAFunan", file: "NiDAFunan.ttf" },
  { label: "NiDAKhmerEmpire", file: "NiDAKhmerEmpire.ttf" },
  { label: "NiDASowanaphum", file: "NiDASowanaphum.ttf" },
  { label: "NiDATaprom", file: "NiDATaprom.ttf" },
  { label: "Nirmala", file: "Nirmala.ttf" },
  { label: "NirmalaB", file: "NirmalaB.ttf" },
  { label: "NirmalaS", file: "NirmalaS.ttf" },
  { label: "Nokora-Bold", file: "Nokora-Bold.ttf" },
  { label: "Nokora-Regular", file: "Nokora-Regular.ttf" },
  { label: "NotoSansCham-Regular", file: "NotoSansCham-Regular.ttf" },
  { label: "NotoSansKhmer-Bold", file: "NotoSansKhmer-Bold.ttf" },
  { label: "NotoSansKhmer-Regular", file: "NotoSansKhmer-Regular.ttf" },
  { label: "NotoSansKhmerUI-Regular", file: "NotoSansKhmerUI-Regular.ttf" },
  { label: "OCRAEXT", file: "OCRAEXT.TTF" },
  { label: "OLDENGL", file: "OLDENGL.TTF" },
  { label: "ONYX", file: "ONYX.TTF" },
  { label: "OUTLOOK", file: "OUTLOOK.TTF" },
  { label: "OdorMeanChey", file: "OdorMeanChey.ttf" },
  { label: "Oswald-Regular", file: "Oswald-Regular.ttf" },
  { label: "PALSCRI", file: "PALSCRI.TTF" },
  { label: "PAPYRUS", file: "PAPYRUS.TTF" },
  { label: "PARCHM", file: "PARCHM.TTF" },
  { label: "PERB____", file: "PERB____.TTF" },
  { label: "PERBI___", file: "PERBI___.TTF" },
  { label: "PERI____", file: "PERI____.TTF" },
  { label: "PER_____", file: "PER_____.TTF" },
  { label: "PERTILI", file: "PERTILI.TTF" },
  { label: "PERTIBD", file: "PERTIBD.TTF" },
  { label: "PLAYBILL", file: "PLAYBILL.TTF" },
  { label: "POORICH", file: "POORICH.TTF" },
  { label: "PRISTINA", file: "PRISTINA.TTF" },
  { label: "PhnomPOT_Krung_gr", file: "PhnomPOT_Krung_gr.ttf" },
  { label: "Preahvihear", file: "Preahvihear.ttf" },
  { label: "RAGE", file: "RAGE.TTF" },
  { label: "RAVIE", file: "RAVIE.TTF" },
  { label: "REFSPCL", file: "REFSPCL.TTF" },
  { label: "REFSAN", file: "REFSAN.TTF" },
  { label: "ROCC____", file: "ROCC____.TTF" },
  { label: "ROCCB___", file: "ROCCB___.TTF" },
  { label: "ROCK", file: "ROCK.TTF" },
  { label: "ROCKB", file: "ROCKB.TTF" },
  { label: "ROCKBI", file: "ROCKBI.TTF" },
  { label: "ROCKEB", file: "ROCKEB.TTF" },
  { label: "ROCKI", file: "ROCKI.TTF" },
  { label: "RataV53", file: "RataV53.ttf" },
  { label: "Romnea-Italic", file: "Romnea-Italic.ttf" },
  { label: "SN KH RANGERFORCE", file: "SN KH RANGERFORCE.ttf" },
  { label: "SN KH SIMPLE", file: "SN KH SIMPLE.otf" },
  { label: "SN KH SIMPLE-HAIR", file: "SN KH SIMPLE-HAIR.ttf" },
  { label: "SN Kh Damril-Pagoda", file: "SN Kh Damril-Pagoda.ttf" },
  { label: "SN Kh Khviek", file: "SN Kh Khviek.ttf" },
  { label: "SN Kh Menghorn", file: "SN Kh Menghorn.ttf" },
  { label: "SN Kh New", file: "SN Kh New.otf" },
  { label: "SN Kh SONY Moul", file: "SN Kh SONY Moul.ttf" },
  { label: "SN Kh Writhand", file: "SN Kh Writhand.otf" },
  { label: "SN Kh Writhand 2", file: "SN Kh Writhand 2.ttf" },
  { label: "SCHLBKB", file: "SCHLBKB.TTF" },
  { label: "SCHLBKBI", file: "SCHLBKBI.TTF" },
  { label: "SCHLBKI", file: "SCHLBKI.TTF" },
  { label: "SCRIPTBL", file: "SCRIPTBL.TTF" },
  { label: "SHOWG", file: "SHOWG.TTF" },
  { label: "SNAP____", file: "SNAP____.TTF" },
  { label: "STENCIL", file: "STENCIL.TTF" },
  { label: "SamsungKhmer-Regular", file: "SamsungKhmer-Regular.ttf" },
  { label: "Sankor", file: "Sankor.ttf" },
  { label: "SithiManuss", file: "SithiManuss.ttf" },
  { label: "SitkaB", file: "SitkaB.ttc" },
  { label: "SitkaI", file: "SitkaI.ttc" },
  { label: "SitkaZ", file: "SitkaZ.ttc" },
  { label: "Sitka", file: "Sitka.ttc" },
  { label: "SourceSansPro-Black", file: "SourceSansPro-Black.otf" },
  { label: "SourceSansPro-Regular", file: "SourceSansPro-Regular.ttf" },
  { label: "SourceSansPro-Semibold", file: "SourceSansPro-Semibold.ttf" },
  { label: "TACTENG", file: "TACTENG.TTF" },
  { label: "TCB_____", file: "TCB_____.TTF" },
  { label: "TCBI____", file: "TCBI____.TTF" },
  { label: "TCCB____", file: "TCCB____.TTF" },
  { label: "TCCEB", file: "TCCEB.TTF" },
  { label: "TCCM____", file: "TCCM____.TTF" },
  { label: "TCM_____", file: "TCM_____.TTF" },
  { label: "TCMI____", file: "TCMI____.TTF" },
  { label: "TEMPSITC", file: "TEMPSITC.TTF" },
  { label: "TaPich", file: "TaPich.ttf" },
  { label: "Taprom", file: "Taprom.ttf" },
  { label: "TimbreKampuchea", file: "TimbreKampuchea.ttf" },
  { label: "Tlok", file: "Tlok.ttf" },
  { label: "U4SvaytonNew", file: "U4SvaytonNew.ttf" },
  { label: "VANTHEAR", file: "VANTHEAR.TTF" },
  { label: "VINERITC", file: "VINERITC.TTF" },
  { label: "VIVALDII", file: "VIVALDII.TTF" },
  { label: "VLADIMIR", file: "VLADIMIR.TTF" },
  { label: "WWDesigns", file: "WWDesigns.ttf" },
  { label: "WWFreebie", file: "WWFreebie.ttf" },
  { label: "WINGDNG2", file: "WINGDNG2.TTF" },
  { label: "WINGDNG3", file: "WINGDNG3.TTF" },
  { label: "YuGothB", file: "YuGothB.ttc" },
  { label: "YuGothL", file: "YuGothL.ttc" },
  { label: "YuGothM", file: "YuGothM.ttc" },
  { label: "YuGothR", file: "YuGothR.ttc" },
  { label: "ZWAdobeF", file: "ZWAdobeF.TTF" },
  { label: "aphireak1", file: "aphireak1.ttf" },
  { label: "arial", file: "arial.ttf" },
  { label: "arialbi", file: "arialbi.ttf" },
  { label: "arialbd", file: "arialbd.ttf" },
  { label: "ariali", file: "ariali.ttf" },
  { label: "ariblk", file: "ariblk.ttf" },
  { label: "bahnschrift", file: "bahnschrift.ttf" },
  { label: "calibri", file: "calibri.ttf" },
  { label: "calibrib", file: "calibrib.ttf" },
  { label: "calibrii", file: "calibrii.ttf" },
  { label: "calibril", file: "calibril.ttf" },
  { label: "calibrili", file: "calibrili.ttf" },
  { label: "calibriz", file: "calibriz.ttf" },
  { label: "cambria", file: "cambria.ttc" },
  { label: "cambriab", file: "cambriab.ttf" },
  { label: "cambriai", file: "cambriai.ttf" },
  { label: "cambriaz", file: "cambriaz.ttf" },
  { label: "comic", file: "comic.ttf" },
  { label: "comicbd", file: "comicbd.ttf" },
  { label: "comici", file: "comici.ttf" },
  { label: "comicz", file: "comicz.ttf" },
  { label: "consola", file: "consola.ttf" },
  { label: "consolab", file: "consolab.ttf" },
  { label: "consolai", file: "consolai.ttf" },
  { label: "consolaz", file: "consolaz.ttf" },
  { label: "constan", file: "constan.ttf" },
  { label: "constanb", file: "constanb.ttf" },
  { label: "constani", file: "constani.ttf" },
  { label: "constanz", file: "constanz.ttf" },
  { label: "corbel", file: "corbel.ttf" },
  { label: "corbelb", file: "corbelb.ttf" },
  { label: "corbeli", file: "corbeli.ttf" },
  { label: "corbelli", file: "corbelli.ttf" },
  { label: "corbell", file: "corbell.ttf" },
  { label: "corbelz", file: "corbelz.ttf" },
  { label: "cour", file: "cour.ttf" },
  { label: "courbi", file: "courbi.ttf" },
  { label: "courbd", file: "courbd.ttf" },
  { label: "couri", file: "couri.ttf" },
  { label: "daunpenh", file: "daunpenh.ttf" },
  { label: "ebrima", file: "ebrima.ttf" },
  { label: "ebrimabd", file: "ebrimabd.ttf" },
  { label: "framd", file: "framd.ttf" },
  { label: "framdit", file: "framdit.ttf" },
  { label: "gadugi", file: "gadugi.ttf" },
  { label: "gadugib", file: "gadugib.ttf" },
  { label: "georgia", file: "georgia.ttf" },
  { label: "georgiab", file: "georgiab.ttf" },
  { label: "georgiai", file: "georgiai.ttf" },
  { label: "georgiaz", file: "georgiaz.ttf" },
  { label: "iKampuchea001 O'Chrov", file: "iKampuchea001_O'Chrov.ttf" },
  { label: "iKampuchea002 KhmerFeeling", file: "iKampuchea002 KhmerFeeling.ttf" },
  { label: "iSeth First", file: "iSeth First.ttf" },
  { label: "iSeth Pi", file: "iSeth Pi.ttf" },
  { label: "iSeth Z11", file: "iSeth Z11.ttf" },
  { label: "impact", file: "impact.ttf" },
  { label: "kMon40hV2E3s", file: "kMon40hV2E3s.ttf" },
  { label: "kMons40V2E3", file: "kMons40V2E3.ttf" },
  { label: "kMons40dicV2E3s", file: "kMons40dicV2E3s.ttf" },
  { label: "kMons40spcV2E3s", file: "kMons40spcV2E3s.ttf" },
  { label: "kMons60bV2E3s", file: "kMons60bV2E3s.ttf" },
  { label: "kMons80V1E2s", file: "kMons80V1E2s.ttf" },
  { label: "kMons99V1E2s", file: "kMons99V1E2s.ttf" },
  { label: "khmer M1.volt", file: "khmer M1.volt.ttf" },
  { label: "khmer M2.volt", file: "khmer M2.volt.ttf" },
  { label: "khmer Samady KS-v2", file: "khmer Samady KS-v2 .ttf" },
  { label: "khmer Savuth", file: "khmer Savuth.ttf" },
  { label: "khmer Savuth Brush", file: "khmer Savuth Brush.ttf" },
  { label: "khmer Savuth Romeas", file: "khmer Savuth Romeas.ttf" },
  { label: "khmer ikhmerstudents", file: "khmer ikhmerstudents.ttf" },
  { label: "khmer s1.volt", file: "khmer s1.volt.ttf" },
  { label: "khmer s2.volt", file: "khmer s2.volt.ttf" },
  { label: "khmer s3.volt", file: "khmer s3.volt.ttf" },
  { label: "khmer s4.volt", file: "khmer s4.volt.ttf" },
  { label: "khmer victorya jrung", file: "khmer_victorya_jrung.ttf" },
  { label: "khmer victorya treykrim", file: "khmer_victorya_treykrim.ttf" },
  { label: "kmSBBICsf", file: "kmSBBICsf.ttf" },
  { label: "kmSBBICsys", file: "kmSBBICsys.ttf" },
  { label: "l_10646", file: "l_10646.ttf" },
  { label: "lucon", file: "lucon.ttf" },
  { label: "malgun", file: "malgun.ttf" },
  { label: "malgunbd", file: "malgunbd.ttf" },
  { label: "malgunsl", file: "malgunsl.ttf" },
  { label: "micross", file: "micross.ttf" },
  { label: "mingliub", file: "mingliub.ttc" },
  { label: "mmrtext", file: "mmrtext.ttf" },
  { label: "mmrtextb", file: "mmrtextb.ttf" },
  { label: "mond40uhgs", file: "mond40uhgs.ttf" },
  { label: "monbaiti", file: "monbaiti.ttf" },
  { label: "moolbor", file: "moolbor.ttf" },
  { label: "msgothic", file: "msgothic.ttc" },
  { label: "msjh", file: "msjh.ttc" },
  { label: "msjhbd", file: "msjhbd.ttc" },
  { label: "msjhl", file: "msjhl.ttc" },
  { label: "msyh", file: "msyh.ttc" },
  { label: "msyhbd", file: "msyhbd.ttc" },
  { label: "msyhl", file: "msyhl.ttc" },
  { label: "msyi", file: "msyi.ttf" },
  { label: "mvboli", file: "mvboli.ttf" },
  { label: "ntailu", file: "ntailu.ttf" },
  { label: "ntailub", file: "ntailub.ttf" },
  { label: "palab", file: "palab.ttf" },
  { label: "palabi", file: "palabi.ttf" },
  { label: "palai", file: "palai.ttf" },
  { label: "pala", file: "pala.ttf" },
  { label: "phagspa", file: "phagspa.ttf" },
  { label: "phagspab", file: "phagspab.ttf" },
  { label: "segmdl2", file: "segmdl2.ttf" },
  { label: "segoepr", file: "segoepr.ttf" },
  { label: "segoeprb", file: "segoeprb.ttf" },
  { label: "segoesc", file: "segoesc.ttf" },
  { label: "segoescb", file: "segoescb.ttf" },
  { label: "segoeui", file: "segoeui.ttf" },
  { label: "segoeuib", file: "segoeuib.ttf" },
  { label: "segoeuii", file: "segoeuii.ttf" },
  { label: "segoeuil", file: "segoeuil.ttf" },
  { label: "segoeuisl", file: "segoeuisl.ttf" },
  { label: "segoeuiz", file: "segoeuiz.ttf" },
  { label: "seguibl", file: "seguibl.ttf" },
  { label: "seguibli", file: "seguibli.ttf" },
  { label: "seguiemj", file: "seguiemj.ttf" },
  { label: "seguihis", file: "seguihis.ttf" },
  { label: "seguili", file: "seguili.ttf" },
  { label: "seguisb", file: "seguisb.ttf" },
  { label: "seguisbi", file: "seguisbi.ttf" },
  { label: "seguisli", file: "seguisli.ttf" },
  { label: "seguisym", file: "seguisym.ttf" },
  { label: "simsun", file: "simsun.ttc" },
  { label: "simsunb", file: "simsunb.ttf" },
  { label: "symbol", file: "symbol.ttf" },
  { label: "symmetricthings2", file: "symmetricthings2.ttf" },
  { label: "sylfaen", file: "sylfaen.ttf" },
  { label: "tahoma", file: "tahoma.ttf" },
  { label: "tahomabd", file: "tahomabd.ttf" },
  { label: "taile", file: "taile.ttf" },
  { label: "taileb", file: "taileb.ttf" },
  { label: "teamviewer15", file: "teamviewer15.otf" },
  { label: "text05a", file: "text05a.ttf" },
  { label: "times", file: "times.ttf" },
  { label: "timesbd", file: "timesbd.ttf" },
  { label: "timesbi", file: "timesbi.ttf" },
  { label: "timesi", file: "timesi.ttf" },
  { label: "trebuc", file: "trebuc.ttf" },
  { label: "trebucbd", file: "trebucbd.ttf" },
  { label: "trebucbi", file: "trebucbi.ttf" },
  { label: "trebucit", file: "trebucit.ttf" },
  { label: "unispace bd", file: "unispace bd.ttf" },
  { label: "verdana", file: "verdana.ttf" },
  { label: "verdanab", file: "verdanab.ttf" },
  { label: "verdanai", file: "verdanai.ttf" },
  { label: "verdanaz", file: "verdanaz.ttf" },
  { label: "wedding", file: "wedding.ttf" },
  { label: "webdings", file: "webdings.ttf" },
  { label: "wingding", file: "wingding.ttf" },
  { label: "wmdance", file: "wmdance.ttf" },
  { label: "wmflower3", file: "wmflower3.ttf" },
  { label: "wmflowers1", file: "wmflowers1.ttf" },
  { label: "wmwedding", file: "wmwedding.ttf" },
];
